language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

matrix:
  include:
    - os: osx
      language: sh
      python: "3.7"
      # Perform the manual steps on osx to install python3 and activate venv
      before_install:
        - brew update
        - brew upgrade python3
        - python3 -m pip install virtualenv
        - virtualenv .venv -p python3
        - source .venv/bin/activate
    - os: windows
      language: sh
      python: "3.7"
      before_install:
        - choco install python3 --params "/InstallDir:C:\\Python" --version 3.7.4
        - export PATH="/c/Python:/c/Python/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel

branches:
  only:
  - master

cache: pip

install:
- pip install -r requirements.txt
- pip install -U pytest pytest-cov codecov

script:
- pytest mgc/

after_success:
- codecov

notifications:
- email: false