language: python

python:
- '3.5'
- '3.6'
- '3.7'

branches:
  only:
  - master

cache: pip

install:
- pip install -r requirements.txt
- pip install -U pytest pytest-cov codecov

script:
- pytest mgc/

after_success:
- codecov

notifications:
- email: false