dist: xenial

sudo: true

language: python

python:
- '3.5'
- '3.6'

matrix:
  include:
    - python: 3.7

cache: pip

install:
- pip install -r requirements.txt
- pip install -U pytest pytest-cov codecov
- if [[ $TRAVIS_PYTHON_VERSION != '3.5' ]]; then travis_retry pip install black; fi

script:
- pytest graspy/ tests/
- if [[ $TRAVIS_PYTHON_VERSION != '3.5' ]]; then black --check --diff ./graspy ./tests; fi

after_success:
- codecov