dist: xenial

sudo: true

language: python

python:
- '3.5'
- '3.6'

matrix:
  include:
    - python: 3.7

cache: pip

install:
- pip install -r requirements.txt
- python3 setup.py install

script:
- py.test -s --cov=mgcpy

after_success:
- codecov